apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"server","app.kubernetes.io/name":"argocd-server","app.kubernetes.io/part-of":"argocd"},"name":"argocd-server","namespace":"argocd"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080},{"name":"https","port":443,"protocol":"TCP","targetPort":8080}],"selector":{"app.kubernetes.io/name":"argocd-server"}}}
  creationTimestamp: "2024-11-03T18:29:49Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
  resourceVersion: "116808"
  uid: 09f796a0-4986-487c-b838-613153ccc646
spec:
  clusterIP: 10.111.218.184
  clusterIPs:
  - 10.111.218.184
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30080  # Voeg de gewenste NodePort toe
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 30443  # Voeg de gewenste NodePort toe
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: NodePort  # Wijzig het type van ClusterIP naar NodePort

status:
  loadBalancer: {}
